---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 512

suites:
  - name: default
    run_list:
      - recipe[webserver_wp::default]
    attributes:
      webserver_wp:
        database:
          root_password: 'mysql_root_password'
          admin_password: 'mysql_admin_password'